import React, { useState, useEffect } from "react";
import DefaultLayout from "../../components/DefaultLayout";
import Typography from "@mui/material/Typography";
import Paper from "@mui/material/Paper";
import { Button, Container } from "@mui/material";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { DatePicker } from "@mui/x-date-pickers/DatePicker";
import List from "@mui/material/List";
import ExpenseItem from "../../components/ExpenseItem";
import TextField from "@mui/material/TextField";
